# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f632a54b57269639c76dadfe97bf241a1369b70140ede5387fb1becee0735b0f99f7a10177e4e7ee5fcd242f878aa675e9e2e534560db308b9c4c48538cb5872

test:
  secret_key_base: 5b7621bba3350d444b77d9b15539ad02301957e31bf5e2746fa039eef51b247957df25358edf3ef80b57143bcebea47bddfe877888f99e7b44e2ce27360715d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
